baseURL: "https://sbwatts.github.io"
title: Seth Watts
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3


params:
    description: "I am a postdoctoral researcher at Arizona State University in the Center for Violence Prevention and Community Safety, and an incoming assistant professor at Texas State University."
    author: Seth Watts
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers", "courses"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Seth Watts, PhD
          subtitle: "I am a postdoctoral researcher at Arizona State University in the Center for Violence Prevention and Community Safety, and an incoming assistant professor at Texas State University. My research focuses on policing, technology, and public health."
          #imageUrl: "headshot.jpg"
          #imageWidth: 180
          #imageHeight: 180
          buttons:
            - name: papers
              url: papers/
            - name: teaching
              url: courses/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:swatts12@asu.edu
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=_zgKKS0AAAAJ&hl=en&oi=ao
        - name: GitHub
          url: https://github.com/sBwatts
        - name: Twitter
          url: https://x.com/SethBWatts

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Seth Watts"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2